language: node_js
node_js: node
deploy:
  provider: heroku
  services: MongoDB
  api_key: 
    secure: XmjYhasiMuHSZAQSXQgQOZUMaFO9LIOHfYdAkf0+IGONeY9qRBqZb9KFQgpjEmfqc3Ru2XW04sdawKH0RFEH3T8IosklakgYDh45pANC3qZiLvk3kTNeAhw1IbhcMrH1BsMT77dpFYGL2t0mWFXpRII+1s7O9BBSvggks5nyibJAaI8SsaPL5mfz+hAoMaROkBvQbvEzLYheuV0UfjXDEZMjyJ1K0C/AYZboyfD51T/V5fV8YFF2zS1KAHSZb5BjC4F2/iMcuFWjIULnExPxxTOy4ubvtMVxktgYRCZcqTvR1F2cwMjLXi2hLI+dBMgltHiox2nnU+dJjFtknrfpjEyseo/XpgaX3A87WI/K74FtB+CY2jjOUmJgswuI5ZCYT3I5F+hCmOemIMKUcj7QYJBw5RmO6ZP4jMQja7+qoY41DuGkeZVhcG87WQ/r/E2CdM9aeRZhxzXKAdaucMDSdDYfkx6vCDXlnfTPTaK7yEq+m5Y2jqUONZJG82n5rkWKKr8mQN38Iu5HkLBC5c6msL2h9X8zVUgAHMYaR7gt6kiNQRQY+IRYrk3yZCS6ks2WAnFxVcWHaM4SwdfT07PN5U5srs4wt4JZGbI+htHohO4cdjGEzLridcPthki7LRrMF+t3bXCT0WU4YlRE6M3jMdy73rrNqkFmntlmS7461UU=
  app: intense-reef-15875
  on:
    repo: SMuyesser/thevideoshelf
before_script: chmod 0777 ./node_modules/.bin/mocha